# Generated by Django 4.2 on 2024-03-09 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_detalis_remove_blog_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='Name',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='Slug',
            field=models.SlugField(default=0),
            preserve_default=False,
        ),
    ]
