# Generated by Django 4.2 on 2024-03-09 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blog_name_blog_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog_Detalis',
        ),
        migrations.AddField(
            model_name='blog',
            name='Description',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog',
            name='Slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
