# Generated by Django 4.2 on 2024-03-08 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Opening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('description', models.TextField(max_length=300)),
                ('image1', models.ImageField(upload_to='opening photos')),
                ('image2', models.ImageField(upload_to='opening photos')),
                ('image3', models.ImageField(upload_to='opening photos')),
                ('event_word', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='projects photos')),
                ('title', models.CharField(max_length=20)),
                ('owner_name', models.CharField(max_length=20)),
                ('description', models.TextField(max_length=300)),
            ],
        ),
    ]
