# Generated by Django 4.2 on 2024-03-08 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='opening',
            old_name='description',
            new_name='description1',
        ),
        migrations.AddField(
            model_name='opening',
            name='description2',
            field=models.TextField(default=0, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='opening',
            name='description3',
            field=models.TextField(default=0, max_length=300),
            preserve_default=False,
        ),
    ]
