# Generated by Django 4.2 on 2024-03-08 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_description_opening_description1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='opening',
            old_name='image1',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='opening',
            name='description2',
        ),
        migrations.RemoveField(
            model_name='opening',
            name='description3',
        ),
        migrations.RemoveField(
            model_name='opening',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='opening',
            name='image3',
        ),
    ]
