# Generated by Django 4.2 on 2024-03-08 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_image1_opening_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Openingthree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('description1', models.TextField(max_length=300)),
                ('image', models.ImageField(upload_to='opening photos')),
                ('event_word', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Openingtow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('description1', models.TextField(max_length=300)),
                ('image', models.ImageField(upload_to='opening photos')),
                ('event_word', models.CharField(max_length=20)),
            ],
        ),
        migrations.RenameModel(
            old_name='Opening',
            new_name='Openingone',
        ),
    ]
