# Generated by Django 4.2 on 2024-03-09 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_projects_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openingone',
            name='image',
            field=models.ImageField(upload_to='static/opening photos'),
        ),
        migrations.AlterField(
            model_name='openingthree',
            name='image',
            field=models.ImageField(upload_to='static/opening photos'),
        ),
    ]
