# Generated by Django 4.2 on 2024-03-09 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_openingone_image_alter_openingthree_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openingone',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='openingthree',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='openingtow',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
