# Generated by Django 4.2 on 2024-03-09 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compitition', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Questions_List',
            new_name='Questions',
        ),
    ]
