# Generated by Django 4.2 on 2024-03-09 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compitition', '0002_rename_questions_list_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='name',
            field=models.CharField(default=0, max_length=40),
            preserve_default=False,
        ),
    ]
