# Generated by Django 4.2 on 2024-03-12 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compitition', '0003_questions_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='date',
            field=models.DateTimeField(default=0),
            preserve_default=False,
        ),
    ]
