# Generated by Django 4.2 on 2024-03-12 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compitition', '0004_questions_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
