# Generated by Django 4.2 on 2024-03-12 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compitition', '0005_alter_questions_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='date',
        ),
    ]
