# Generated by Django 4.2 on 2024-03-21 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compitition', '0007_questions_published_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='published_at',
        ),
        migrations.AddField(
            model_name='questions',
            name='logo',
            field=models.ImageField(default=1, upload_to='comp'),
            preserve_default=False,
        ),
    ]
